import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';

export const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});
import { cn } from '@/lib/utils';
import NavMenu from '@/components/NavMenu';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <NavMenu />
        {children}
      </body>
    </html>
  );
}
